[package]
name = "snek-tui"
version = "0.1.0"
edition = "2021"
discription = "Snake TUI Game"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.26.1"
tui = "0.19.0"
